<a href="https://colab.research.google.com/github/Morioh/math_for_ml/blob/main/Summative_Assignment_PCA_Mourice_Onyonyi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



<center>
    <img src="https://miro.medium.com/v2/resize:fit:300/1*mgncZaKaVx9U6OCQu_m8Bg.jpeg">
</center>



The goal of PCA is to extract information while reducing the number of features
from a dataset by identifying which existing features relate to another. The crux of the algorithm is trying to determine the relationship between existing features, called principal components, and then quantifying how relevant these principal components are. The principal components are used to transform the high dimensional data to a lower dimensional data while preserving as much information. For a principal component to be relevant, it needs to capture information about the features. We can determine the relationships between features using covariance.

In [ ]:
#import necessary package
#TO DO


In [ ]:

data = np.array([
    [   1,   2,  -1,   4,  10],
    [   3,  -3,  -3,  12, -15],
    [   2,   1,  -2,   4,   5],
    [   5,   1,  -5,  10,   5],
    [   2,   3,  -3,   5,  12],
    [   4,   0,  -3,  16,   2],
])

### Step 1: Standardize the Data along the Features

![image.png](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLxe5VYCBsaZddkkTZlCY24Yov4JJD4-ArTA&usqp=CAU)




Explain why we need to handle the data on the same scale.

**[TO DO: Insert Answer here]**

In [ ]:


standardized_data = #TO DO:  Insert code here

![cov matrix.webp](https://dmitry.ai/uploads/default/original/1X/9bd2851674ebb55e404cc3ff5e2ffe65b42ff460.png)

We use the pair - wise covariance of the different features to determine how they relate to each other. With these covariances, our goal is to group / cluster based on similar patterns. Intuitively, we can relate features if they have similar covariances with other features.

### Step 2: Calculate the Covariance Matrix



In [ ]:

cov_matrix = #TO DO: insert code here

print()

[[  1.80555556  -0.88888889  -1.47222222   4.58333333  -3.63888889]
 [ -0.88888889   3.55555556   0.38888889  -5.5         16.38888889]
 [ -1.47222222   0.38888889   1.47222222  -2.75         1.97222222]
 [  4.58333333  -5.5         -2.75        20.58333333 -23.25      ]
 [ -3.63888889  16.38888889   1.97222222 -23.25        77.13888889]]


### Step 3: Eigendecomposition on the Covariance Matrix


In [ ]:


eigenvalues, eigenvectors = #TO DO: Insert code here for eigenvalues, eigenvectors

### Step 4: Sort the Principal Components
# np.argsort can only provide lowest to highest; use [::-1] to reverse the list

In [ ]:
# np.argsort can only provide lowest to highest; use [::-1] to reverse the list

order_of_importance = #TO DO: insert code here
print ( 'the order of importance is :\n {}'.format(order_of_importance))

# utilize the sort order to sort eigenvalues and eigenvectors
sorted_eigenvalues = eigenvalues[#TO DO: insert code here]

print('\n\n sorted eigen values:\n{}'.format(sorted_eigenvalues))
sorted_eigenvectors = eigenvectors[#TO DO: insert code here] # sort the columns
print('\n\n The sorted eigen vector matrix is: \n {}'.format(sorted_eigenvectors))

the order of importance is :
 [0 1 2 3 4]


 sorted eigen values:
[8.93539590e+01 1.34853157e+01 1.60978112e+00 1.06316451e-01
 1.83336468e-04]


 The sorted eigen vector matrix is: 
 [[-0.05817655 -0.2631212   0.57237125  0.6292347  -0.45148374]
 [ 0.19774895 -0.03283879  0.06849106 -0.60720902 -0.7657827 ]
 [ 0.0328828   0.17887983 -0.75671562  0.45776292 -0.42983171]
 [-0.33200499 -0.88598416 -0.30234056 -0.11461168  0.01609676]
 [ 0.91989252 -0.33574235 -0.06059523  0.11259736  0.15724145]]


Question:

1. Why do we order eigen values and eigen vectors?

[Insert Answer here]

2. Is it true we would consider the lowest eigen value compared to the highest? Defend your answer

[insert answer here]


You want to see what percentage of information each eigen value holds. You would have print out the percentage of each eigen value using the formula



> (sorted eigen values / sum of all sorted eigen values) * 100



In [ ]:
# use sorted_eigenvalues to ensure the explained variances correspond to the eigenvectors

#TO DO: Insert code here
explained_variance = #TO DO: insert code here
explained_variance =["{:.2f}%".format(value) for value in explained_variance]
print( explained_variance)

['85.46%', '12.90%', '1.54%', '0.10%', '0.00%']


#Initialize the number of Principle components then perfrom matrix multiplication with the variable K example k = 3 for 3 priciple components




> The reulting matrix (with reduced data) = standardized data * vector with columns k

See expected output for k = 2



In [ ]:
k =  # select the number of principal components

reduced_data = #TO DO: Insert code here
reduced_data = np.matmul(#TO DO: insert code here)[#TO DO: insert code here] # transform the original data

In [ ]:
print(reduced_data)

[[ 1.07127878 -0.6983307 ]
 [-3.49014682 -0.59870297]
 [ 0.24003422 -0.48244534]
 [-0.14516166 -1.61189378]
 [ 1.34022572 -1.07434063]
 [-0.96573453 -2.23341502]]


In [ ]:
print(reduced_data.shape)

(6, 2)


# *What are 2 positive effects and 2 negative effects of PCA

Give 2 Benefits and 2 limitations
[insert answer here]